name: Simple pipeline to build firmware and save generated image
on:
  push:
  schedule:
    - cron:  "5 19 * * *" #build project everyday at hour 3, minute 7, and hour 15 and minute 7 (aka 3:07 and 15:07)

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: INIT
      uses: actions/checkout@master
    run: |
      sudo apt-get update
      echo "UPDATED PACKAGES WITH THE ONES IN THE UBUNTU REPOSITORY"
